server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-usuarios
          uri: lb://ms-usuarios
          predicates:
            - Path=/api/usuarios/**
          filters:
            - name: CircuitBreaker
              args:
                name: usuariosCB
                fallbackUri: forward:/fallback/usuarios

        - id: ms-categorias
          uri: lb://ms-categorias
          predicates:
            - Path=/api/categorias/**
          filters:
            - name: CircuitBreaker
              args:
                name: categoriasCB
                fallbackUri: forward:/fallback/categorias

        - id: ms-bodega
          uri: lb://ms-bodega
          predicates:
            - Path=/api/ubicaciones/**
          filters:
            - name: CircuitBreaker
              args:
                name: bodegaCB
                fallbackUri: forward:/fallback/bodega

        - id: ms-proveedores
          uri: lb://ms-proveedores
          predicates:
            - Path=/api/proveedores/**
          filters:
            - name: CircuitBreaker
              args:
                name: proveedoresCB
                fallbackUri: forward:/fallback/proveedores

        - id: ms-producto
          uri: lb://ms-producto
          predicates:
            - Path=/api/productos/**
          filters:
            - name: CircuitBreaker
              args:
                name: productoCB
                fallbackUri: forward:/fallback/producto

        - id: ms-kardex
          uri: lb://ms-kardex
          predicates:
            - Path=/api/kardex/**
          filters:
            - name: CircuitBreaker
              args:
                name: kardexCB
                fallbackUri: forward:/fallback/kardex

        - id: ms-ingresos
          uri: lb://ms-ingresos
          predicates:
            - Path=/api/ingresos/**
          filters:
            - name: CircuitBreaker
              args:
                name: ingresosCB
                fallbackUri: forward:/fallback/ingresos

        - id: ms-egresos
          uri: lb://ms-egresos
          predicates:
            - Path=/api/egresos/**
          filters:
            - name: CircuitBreaker
              args:
                name: egresosCB
                fallbackUri: forward:/fallback/egresos

        - id: ms-ajuste
          uri: lb://ms-ajuste
          predicates:
            - Path=/api/ajustes/**
          filters:
            - name: CircuitBreaker
              args:
                name: ajusteCB
                fallbackUri: forward:/fallback/ajuste

        - id: ms-traslados
          uri: lb://ms-traslados
          predicates:
            - Path=/api/traslados/**
          filters:
            - name: CircuitBreaker
              args:
                name: trasladosCB
                fallbackUri: forward:/fallback/traslados

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    healthcheck:
      enabled: true
instance:
    prefer-ip-address: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME:ms-gateway-k273.onrender.com}
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

spring.cloud.gateway.httpclient:
  connect-timeout: 10000
  response-timeout: 30s